server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java

playlistEntity Mapping을 위한 1차구현
1. playlist Entity 1차 구현
entity mapping을 위한 1차 entity구현입니다

:sparkles: feat : playlistEntity 1차 구현

---

server/server/src/main/java/com/mainproject/server/config/auth/WebSecurityConfigurerAdapter.java
server/server/src/main/java/com/mainproject/server/config/auth/dto/OAuthAttributes.java
server/server/src/main/java/com/mainproject/server/config/auth/dto/SessionMember.java
server/server/src/main/java/com/mainproject/server/exception/BusinessException.java
server/server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
server/server/src/main/java/com/mainproject/server/member/dto/MemberFollowDto.java
server/server/src/main/java/com/mainproject/server/member/dto/MemberPatchDto.java
server/server/src/main/java/com/mainproject/server/member/dto/MemberPostDto.java
server/server/src/main/java/com/mainproject/server/member/dto/MemberResponseDto.java
server/server/src/main/java/com/mainproject/server/member/entity/Follow.java
server/server/src/main/java/com/mainproject/server/member/entity/Member.java
server/server/src/main/java/com/mainproject/server/member/entity/Ranking.java
server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
server/server/src/main/java/com/mainproject/server/member/repository/MemberRepository.java
server/server/src/main/java/com/mainproject/server/member/service/CustomOAuth2UserService.java
server/server/src/main/java/com/mainproject/server/member/service/MemberService.java
server/server/src/main/java/com/mainproject/server/response/MultiResponseDto.java
server/server/src/main/java/com/mainproject/server/response/PageInfo.java
server/server/src/main/java/com/mainproject/server/response/SingleResponseDto.java

1. Single, Multi response(pageinfo)
2. BusinessException, ExceptionCode
3. member patch get(post는 OAuth로)

response, exception, member 기본기능

---

client/package-lock.json
client/package.json
client/src/components/Mypage/Content.tsx
client/src/components/Mypage/MypageContents.tsx
client/src/components/Mypage/MypageInfo.tsx
client/src/components/common/BookMark.tsx
client/src/components/common/Button.tsx
client/src/components/common/Toggle.tsx
client/src/components/playlist/MusicList.tsx
client/src/components/playlist/PlayListInfo.tsx
client/src/components/playlist/PlayListSetting.tsx
client/src/components/playlistcollection/CplayList.tsx
client/src/pages/Mypage.tsx
client/src/pages/PlayListCollection.tsx
client/src/pages/PlayListDetail.tsx
client/src/pages/PlayListModify.tsx
client/src/routes/AppRouter.tsx

1. 마이페이지 화면 구현
- 플리 넘길때 react swiper 사용 
- pull 받고 npm install 해야함
3. 마이페이지 > 나의 플레이리스트 화면 구현
4. 디자인 수정사항 반영 완료

✨Feat: 마이페이지 1차 구현 완료

---

server/server/src/main/java/com/mainproject/server/auth/config/WebConfig.java
server/server/src/main/java/com/mainproject/server/auth/config/WebSecurityConfigurerAdapter.java
server/server/src/main/java/com/mainproject/server/auth/dto/OAuthAttributes.java
server/server/src/main/java/com/mainproject/server/auth/dto/SessionMember.java
server/server/src/main/java/com/mainproject/server/auth/handler/OAuth2SuccessHandler.java
server/server/src/main/java/com/mainproject/server/member/dto/SimpleMemberResponseDto.java
server/server/src/main/java/com/mainproject/server/member/jwt/JwtTokenizer.java
server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
server/server/src/main/java/com/mainproject/server/member/service/CustomOAuth2UserService.java

1. JWT 설정
2. 로그인 로그아웃 권한설정 구현
3. SimpleMember Dto

✨ feat : JWT로그인, 심플DTO

---

client/data/data.json
client/src/assets/styles/GlobalStyle.ts
client/src/components/home/Header.tsx
client/src/components/room/Chatting.tsx
client/src/components/room/PeopleList.tsx
client/src/components/room/Playlist.tsx
client/src/components/room/RoomCreateForm.tsx
client/src/components/room/updateModal.tsx
client/src/pages/Room.tsx
client/src/pages/RoomList.tsx
client/src/routes/AppRouter.tsx

1. 방 생성시 data.json으로 추가되게 했습니다. 플레이리스트는 배열, 스트링 둘다 들어갈수 있게 해놨습니다
2. 데이터 추가시 똑같은 썸네일 추가되게 했는데 상대경로라 추출이 안된다면(사용하기 어렵다면) 말씀해주세요

✨Feat : 방 생성 시 json server 데이터 추가

---

.github/workflows/front.yml

1.client 배포 자동화
- dev 브랜치에 push 될때 아래의 url로 빌드-> 배포 하도록 github action 생성
http://luvpli.s3-website.ap-northeast-2.amazonaws.com/
- secret key 등록을 해야됨. 권한이 없음(로그인 테스트할때 불러주십셔)
- env 사용법
1. REACT_APP_STACK_SERVER 이름으로 스크릿 키를 서버 도메인으로 등록(프로젝트의 setting을 들어갈 수 가 없어서 영석님이 해주셔야됩니다.)
2. root.ts 에서 빨간줄 부분 주석 해제하고 위쪽 test 주석 후 PR

✨Feat: client 배포 자동화

---

server/server/src/main/java/com/mainproject/server/auth/config/WebSecurityConfigurerAdapter.java
server/server/src/main/java/com/mainproject/server/auth/handler/OAuth2SuccessHandler.java
server/server/src/main/java/com/mainproject/server/auth/utils/CustomAuthorityUtil.java
server/server/src/main/java/com/mainproject/server/member/dto/MemberResponseDto.java
server/server/src/main/java/com/mainproject/server/member/entity/Member.java
server/server/src/main/java/com/mainproject/server/member/entity/Ranking.java
server/server/src/main/java/com/mainproject/server/member/jwt/JwtTokenizer.java
server/server/src/main/java/com/mainproject/server/member/jwt/RefreshToken.java
server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
server/server/src/main/java/com/mainproject/server/member/repository/TokenRepository.java
server/server/src/main/java/com/mainproject/server/member/service/CustomOAuth2UserService.java

1. member get요청 확인 / 그 외 자잘한 수정

✨ feat : member get요청

---

client/src/pages/MakePlayList.tsx
client/src/pages/PlayListDetail.tsx

1. axios 통신에러시 예외처리 추가
- 정상응답이 아니면 error 를 alert으로 보여줌

🐛Fix: 통신에러시 예외처리 추가

---

client/src/pages/PlaylistList.tsx

🐛Fix: playlistList 대소문자 수정

---

.github/workflows/front.yml

🚀Build: 배포 자동화 변경사항 반영

---

.github/workflows/front.yml
client/src/pages/PlaylistList.tsx

🚀Build: 배포 자동화 테스트

---

.github/workflows/front.yml

🚀Build: front.yml 수정

---

client/.eslintrc.json

🐛Fix: eslint error 수정

---

.github/workflows/front.yml
client/.eslintrc.json

🚀Build: 배포 테스트

---

.github/workflows/front.yml

🚀Build: env 생성

---

client/src/api/root.ts

🐛Fix : withCredentials 제거
- withCredentials : true 하면 유튜브 api에서 cors 나옴

🐛Fix : withCredentials 제거

---

.github/workflows/front.yml
client/src/api/root.ts

🚀Build : 배포 자동화 테스트
- env 정상 생성 완료
- http headers에 credentials: true 여서 유튜브 api cors 에런 나는것 수정

🚀Build : 배포 자동화 테스트

---

server/server/src/main/java/com/mainproject/server/ServerApplication.java
server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPostDto.java
server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java

:hammer: chore : authorization추가, 짜잘한 수정

---

server/server/src/main/java/com/mainproject/server/ChatRoom/controller/RoomController.java
server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ResponseChatRoomDto.java
server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java

1. follow 요청 보냈을 때, follow 요청 이후 멤버의 정보를 조회하도록 변경
2. 자잘한 수정

🐛 fix : follow test

---

server/server/src/main/java/com/mainproject/server/ChatRoom/controller/ChatController.java
server/server/src/main/java/com/mainproject/server/ChatRoom/entity/ChatMessage.java
server/server/src/main/java/com/mainproject/server/ChatRoom/entity/ChatRoom.java
server/server/src/main/java/com/mainproject/server/auth/handler/OAuth2SuccessHandler.java

1. chatMessage 연결 / OAuth2 로그인 callback 변경

✨ feat : chatMessage 연결

---

server/server/src/main/java/com/mainproject/server/auth/config/SecurityConfig.java
server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
server/server/src/main/java/com/mainproject/server/member/dto/RankResponseDto.java
server/server/src/main/java/com/mainproject/server/member/entity/Member.java
server/server/src/main/java/com/mainproject/server/member/entity/Ranking.java
server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
server/server/src/main/java/com/mainproject/server/redis/config/RedisConfig.java

✨ feat : ranking

---

client/src/components/Mypage/Content.tsx
client/src/components/Mypage/MypageContents.tsx
client/src/components/common/BookMark.tsx
client/src/components/playlist/PlayListInfo.tsx
client/src/components/playlistcollection/CplayList.tsx
client/src/components/playlistcollection/ModifyButton.tsx
client/src/pages/Mypage.tsx
client/src/pages/PlayListDetail.tsx

✨ Feat: 마이페이지 플리

---

server/server/src/main/java/com/mainproject/server/advice/GlobalExceptionAdvice.java
server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
server/server/src/main/java/com/mainproject/server/member/entity/Follow.java
server/server/src/main/java/com/mainproject/server/member/repository/FollowRepository.java
server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
server/server/src/main/java/com/mainproject/server/playlist/dto/LikePlaylistResponseDto.java
server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPatchDto.java
server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPostDto.java
server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
server/server/src/main/java/com/mainproject/server/playlist/dto/SimplePlaylistResponseDto.java
server/server/src/main/java/com/mainproject/server/playlist/entity/Bookmark.java
server/server/src/main/java/com/mainproject/server/playlist/entity/Category.java
server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
server/server/src/main/java/com/mainproject/server/playlist/repository/BookmarkRepository.java
server/server/src/main/java/com/mainproject/server/playlist/repository/PlaylistItemRepository.java
server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java

1. playlist bookmark
2. 회원이 한 bookmark / follow 조회
3. playlist category, status 추가

✨ feat : bookmark 그외 잡다한것

---

client/data/mypage.json
client/src/api/playlistApi.ts
client/src/api/userApi.ts
client/src/components/Mypage/Content.tsx
client/src/components/Mypage/MypageContents.tsx
client/src/components/common/BookMark.tsx
client/src/components/common/Like.tsx
client/src/components/home/Header.tsx
client/src/components/home/Playlist.tsx
client/src/components/playlist/PlayListInfo.tsx
client/src/components/playlistcollection/CplayList.tsx
client/src/components/playlistcollection/ModifyButton.tsx
client/src/pages/MakePlayList.tsx
client/src/pages/Mypage.tsx
client/src/pages/PlayListCollection.tsx
client/src/pages/PlayListDetail.tsx
client/src/pages/PlaylistList.tsx
client/src/pages/RoomList.tsx
client/src/routes/AppRouter.tsx

1. 플레이리스트 수정,삭제,좋아요,북마크,카테고리,공개/비공개 테스트 완료
2. 마이페이지 플레이리스트 조회 , 팔로우 유저 조회 테스트 완료
3. 기능만 완료됨 디자인 수정은 해야함

✨ Feat: 플레이 리스트 테스트 완료

---

server/server/src/main/java/com/mainproject/server/playlist/dto/LikePlaylistResponseDto.java
server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPatchDto.java
server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPostDto.java
server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
server/server/src/main/java/com/mainproject/server/playlist/dto/SimplePlaylistResponseDto.java
server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java

🔨 chore : CategoryList 변수명 수정

---

client/src/api/roomApi.ts
client/src/components/common/Button.tsx
client/src/components/room/RoomCreateForm.tsx
client/src/components/room/RoomUpdateForm.tsx
client/src/components/room/addModal.tsx
client/src/pages/Main.tsx
client/src/pages/Room.tsx
client/src/slices/mySlice.ts
client/src/slices/playlistSlice.ts
client/src/store/store.ts

✨Feat: 방 생성시 플레이리스트 연동 1차 구현

---

client/src/components/playlist/PlayListInfo.tsx
client/src/pages/PlayListDetail.tsx

🐛 Fix: 플리 상세페이지 유저 프로필 이미지 수정
- 프로필 이미지 유저 본인꺼로 나오게 수정

🐛 Fix: 플리 상세페이지 유저 프로필 이미지 수정

---

client/src/components/playlistcollection/CplayList.tsx
client/src/components/playlistcollection/ModifyButton.tsx
client/src/pages/PlayListCollection.tsx

1. 삭제 후 페이지이동
- 상세 페이지에서 삭제시 뒤로가기
- 컬렉션 페이지 에서 삭제시 데이터 get 한번더함

🐛 Fix: playlist delete navigate

---

client/package-lock.json
client/package.json
client/src/components/home/Room.tsx
client/src/components/room/Playlist.tsx
client/src/components/room/RoomCreateForm.tsx
client/src/components/room/addModal.tsx
client/src/pages/Room.tsx
client/src/pages/RoomList.tsx

1. 채팅방 플리 작동 구현 (플리 안 버튼 기능 간소하게 구현)
2. 유튜브는 소켓통신 안됨
3. 북마크한 플리 방 생성시 연동
4. react-player 설치했는데 결국은 사용 안할것 같습니다 혹시 에러나시면 npm install 하시면 될거 같아요

✨Feat: 채팅방 플리 작동 구현 / 유튜브 소켓은 미적용

---

client/src/api/roomApi.ts
client/src/components/home/Footer.tsx
client/src/components/home/Header.tsx
client/src/components/room/Chatting.tsx
client/src/components/room/PeopleList.tsx
client/src/components/room/Playlist.tsx
client/src/components/room/RoomUpdateForm.tsx
client/src/components/room/userModal.tsx
client/src/pages/Room.tsx
client/src/routes/AppRouter.tsx

1. 인원표시, 방장표시 구현
2 채팅방 플리 기능 수정

✨Feat: 채팅방 플리 수정 / 채팅방 헤더 푸터 삭제 / 방장 표시 / 인원표시 구현

---

server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
server/server/src/main/java/com/mainproject/server/member/repository/MemberRepository.java
server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
server/server/src/main/java/com/mainproject/server/member/service/MemberService.java

1. Member 이름으로 검색 / Following 기능에서 팔로우 상태 확인

✨ feat : Member 검색기능

---

client/src/components/common/BookMark.tsx
client/src/components/common/Like.tsx
client/src/components/playlist/PlayListSetting.tsx
client/src/components/playlistcollection/CplayList.tsx
client/src/components/room/RoomCreateForm.tsx
client/src/pages/PlaylistList.tsx
client/src/pages/RoomList.tsx

✅ 스와이퍼 마우스 오버시 autoplay stop 
✅ 좋아요 자신꺼도 할 수 있게 
✅ 이미지 상하에 검은여백 삭제
✅ 북마크 컬렉션페이지에 북마크 추가
✅ 방생성 모달 input border 디자인 수정

Fix: 여러가지 에러 수정

---

server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
server/server/src/main/java/com/mainproject/server/playlist/repository/PlaylistRepository.java
server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java

1. 플레이리스트 검색기능(제목O, 작성자O, 카테고리X), 북마크 여부 표시

✨ feat : PlSearch

---

client/src/components/room/Chatting.tsx
client/src/components/room/PeopleList.tsx
client/src/components/room/Playlist.tsx
client/src/components/room/RoomCreateForm.tsx
client/src/components/room/RoomUpdateForm.tsx
client/src/components/room/addModal.tsx
client/src/pages/Room.tsx

1. 방 인원 / 방 생성 수정 유효성 검사 / 플리 수정

Feat:✨ 방 인원 / 방 생성 수정 유효성 검사 / 플리 수정

---

server/server/src/main/java/com/mainproject/server/ChatRoom/controller/ChatController.java
server/server/src/main/java/com/mainproject/server/ChatRoom/controller/RoomController.java
server/server/src/main/java/com/mainproject/server/ChatRoom/repository/ChatRoomRepository.java
server/server/src/main/java/com/mainproject/server/ChatRoom/service/ChatService.java
server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java

✨ feat : RoomSearch

---

server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
server/server/src/main/java/com/mainproject/server/playlist/entity/PlaylistItem.java
server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
server/server/src/main/java/com/mainproject/server/playlist/repository/PlaylistRepository.java
server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java

1. title 변수명이 겹쳐서 변수명이 안겹치게 수정

🐛 fix : search 변수명 수정

---

server/server/src/main/java/com/mainproject/server/ChatRoom/controller/RoomController.java
server/server/src/main/java/com/mainproject/server/ChatRoom/service/ChatService.java
server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
server/server/src/main/java/com/mainproject/server/member/service/MemberService.java
server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
server/server/src/main/java/com/mainproject/server/playlist/repository/PlaylistRepository.java
server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java

🔨 chore : search 페이지네이션 추가

---

client/src/api/roomApi.ts
client/src/pages/Room.tsx

✨Feat: 같은 방 내에 동일한 유저 접속 방지 기능 구현

---

server/server/src/main/java/com/mainproject/server/advice/GlobalExceptionAdvice.java
server/server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
server/server/src/main/java/com/mainproject/server/member/dto/MemberPatchDto.java
server/server/src/main/java/com/mainproject/server/member/dto/MemberResponseDto.java
server/server/src/main/java/com/mainproject/server/member/dto/RankResponseDto.java
server/server/src/main/java/com/mainproject/server/member/dto/SimpleMemberResponseDto.java
server/server/src/main/java/com/mainproject/server/member/entity/Member.java
server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
server/server/src/main/java/com/mainproject/server/member/repository/MemberRepository.java
server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
server/server/src/main/java/com/mainproject/server/member/service/MemberService.java
server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
server/server/src/main/java/com/mainproject/server/playlist/dto/LikePlaylistResponseDto.java
server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java

1. Member Grade 기능 (follow, like, ranking api요청때마다 최신화)
2. 중복닉네임 검사, 자기소개 추가

✨ feat : Grade / 중복닉네임검사, 자기소개 추가

---

server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPostDto.java
server/server/src/main/java/com/mainproject/server/playlist/dto/SimplePlaylistResponseDto.java
server/server/src/main/java/com/mainproject/server/playlist/entity/CategoryDetail.java
server/server/src/main/java/com/mainproject/server/playlist/entity/Likes.java
server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java

:sparkles: feat : 좋아요순 정렬 기능 구현

---

server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ResponseChatRoomDto.java
server/server/src/main/java/com/mainproject/server/ChatRoom/mapper/ChatRoomMapper.java
server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
server/server/src/main/java/com/mainproject/server/playlist/repository/PlaylistRepository.java

1. getRoom을 했을때 playlist를 못찾으면 빈값을 반환하게 변경

🐛 fix : getRoom, like

---

client/src/components/common/BookMark.tsx
client/src/components/playlist/MusicList.tsx
client/src/components/playlist/PlayListInfo.tsx
client/src/components/playlist/PlayListSetting.tsx
client/src/components/playlistcollection/CplayList.tsx
client/src/components/room/Playlist.tsx

🐛 Fix: 피드백 수정

---

client/src/assets/styles/GlobalStyle.ts
client/src/components/home/Room.tsx
client/src/components/room/PeopleList.tsx
client/src/components/room/Playlist.tsx
client/src/components/room/RoomCreateForm.tsx
client/src/components/room/RoomUpdateForm.tsx
client/src/components/room/addModal.tsx
client/src/components/room/updateModal.tsx
client/src/pages/Room.tsx
client/src/pages/RoomList.tsx

1. 방에 있는 플리 삭제 시 방 삭제 구현
2.반응형 및 유효성 검사 스타일 개선

 ✨ Feat : 방에 있는 플리 삭제 시 방 삭제 구현

---

client/src/api/root.ts
client/src/components/room/Playlist.tsx
client/src/components/room/addModal.tsx
client/src/pages/Room.tsx

💄Style: 채팅방 스타일 개선 및 방 버그 수정

---

server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java

1. 플레이리스트 삭제할때 연관된 방도 함께 삭제하도록 변경

🐛 fix : PlaylistDelete

---

client/src/components/home/Footer.tsx
client/src/components/home/Header.tsx
client/src/components/room/PeopleList.tsx
client/src/components/room/RoomCreateForm.tsx
client/src/components/room/RoomUpdateForm.tsx
client/src/pages/Room.tsx
client/src/routes/AppRouter.tsx

1. 방 내에서 유저 페이지 / 팔로우 가능 기능 구현
2. 어드민일 경우 방 삭제 안하는 기능 구현

✨Feat: 방 내에서 유저페이지, 팔로우 기능 구현 / 어드민일 경우 방 삭제 안하기 기능 구현

---

client/src/components/common/BookMark.tsx
client/src/components/playlist/PlayListSetting.tsx
client/src/pages/Room.tsx
client/src/pages/RoomList.tsx

🐛 Fix: 오류 수정 및 리팩토링

---

.github/workflows/front.yml
client/src/components/room/RoomCreateForm.tsx
client/src/pages/Room.tsx

🔨Chore: 환경변수 설정  

---

client/src/api/root.ts
client/src/pages/Logout.tsx
client/src/routes/AppRouter.tsx

♻️ Refactor : 리프레시 토큰 로그아웃 로직 수정

♻️ Refactor : 리프레시 토큰 로그아웃 로직 수정

---

client/public/index.html

🚀 Deploy: https 관련 코드 추가

---

client/public/index.html

🚀 Deploy: http 원복

---

client/src/components/room/Playlist.tsx

🔨Chore: 플리 주석 해제

---

client/src/components/home/Room.tsx

🔨Chore: 방 비밀번호 모달 취소 추가

---

client/src/components/room/Playlist.tsx

1. 유튜브 재생시작시간 1초로 고정 및 sandbox 특성 개선

🔨Chore: 유튜브 재생시작시간 1초로 고정 및 sandbox 특성 개선

---

client/.eslintrc.json
client/src/api/root.ts
client/src/components/home/Room.tsx
client/src/components/room/PeopleList.tsx
client/src/components/room/RoomCreateForm.tsx
client/src/pages/Room.tsx
client/src/pages/RoomList.tsx
client/tsconfig.json

🐛Fix : unused vars 제거

---

client/src/components/room/Playlist.tsx

1. 유튜브 플레이어 너비 높이 1 지정
재생 시간 버그 fix

🔨Chore: 유튜브 플레이어 너비 높이 1 지정

---

server/server/src/main/java/com/mainproject/server/ServerApplication.java
server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
server/server/src/main/java/com/mainproject/server/member/entity/Member.java
server/server/src/main/java/com/mainproject/server/member/entity/RankingList.java
server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
server/server/src/main/java/com/mainproject/server/member/repository/MemberRepository.java
server/server/src/main/java/com/mainproject/server/member/repository/RankingListRepository.java
server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
server/server/src/main/java/com/mainproject/server/member/service/RankingScheduler.java
server/server/src/main/java/com/mainproject/server/response/ErrorResponse.java

✨ feat : RankingScheduler

---

server/server/src/main/java/com/mainproject/server/member/dto/RankResponseDto.java
server/server/src/main/java/com/mainproject/server/member/entity/RankingList.java
server/server/src/main/java/com/mainproject/server/member/service/RankingScheduler.java

🔨 chore : RankingTime

---

client/public/index.html

[🚀 Deploy: 배포 https 적용](https://github.com/codestates-seb/seb40_main_014/commit/9cee90da26a15e7ebd1077534bd3ab1ef145ca24)

🚀 Deploy: 배포 https 적용

---

client/src/api/userApi.ts
client/src/components/room/PeopleList.tsx

🔨Chore: getAllUser 어세스토큰 변경

---

client/src/api/userApi.ts
client/src/components/room/PeopleList.tsx
client/src/pages/RoomList.tsx

🚀 Deploy: 배포 테스트

---

client/public/index.html

[🚀 Deploy: 웹소켓 주소 변경](https://github.com/codestates-seb/seb40_main_014/commit/393767a8738939c3f9d94ca1b42317ffd51bdc40)

🚀 Deploy: 웹소켓 주소 변경

---

client/src/pages/Room.tsx

🐛 fix: 버그 콘솔  테스트

---

client/src/pages/PlaylistList.tsx
client/src/pages/RoomList.tsx

🐛 Fix : 에러 확인용 콘솔

---

client/src/pages/Room.tsx

🐛Fix: 배포 테스트

---

client/src/pages/Room.tsx

🔨Chore : 콘솔 제거

---

client/src/pages/PlaylistList.tsx
client/src/pages/RoomList.tsx

[🐛 Fix: 에러 콘솔 제거](https://github.com/codestates-seb/seb40_main_014/commit/59a394fab3f09fcfdba3d3356b84995170c18784)

🐛 Fix: 에러 콘솔 제거

---

client/src/pages/Room.tsx

🔨Chore: 방 입장시 publish setTimeout 설정

---

client/src/pages/Room.tsx

1. 방 입장시 publish setTimeout 설정 변경 및 에러 시 서버 deactivate

🔨Chore: 방 입장시 publish setTimeout 설정 변경 및 에러 시 서버 deactivate

---

client/src/pages/Room.tsx

🐛 Fix: Room ws 에러 콘솔

---

client/src/pages/Room.tsx

🐛 Fix: ws 에러 콘솔

---

client/src/pages/Room.tsx

🐛 Fix: ws error console

---

client/src/pages/Room.tsx

🐛 Fix: ws err console

---

client/src/pages/Room.tsx

♻️ Refactor : 룸 콘솔 제거

---

client/src/pages/Room.tsx

🔨Chore : 웹소켓 리커넥트 시간 변경

---

client/src/pages/Room.tsx

🐛Fix : 웹 소켓 테스트

---

client/src/pages/Room.tsx

🐛Fix : leave 테스트

---

client/src/pages/Room.tsx

🐛Fix : leave 테스트2

---

client/src/pages/Room.tsx

🐛Fix : leave 테스트3

---

client/src/pages/Room.tsx

Fix : leave 테스트3

---

client/src/api/userApi.ts
client/src/pages/Room.tsx

🐛Fix : Follow / 유저페이지 이동 fix

---

client/src/api/userApi.ts
client/src/components/room/PeopleList.tsx

🔨Chore: 버그 픽스2
